### ISSUE TITLE
Transfer to cabinjs org on GitHub and npm owner add niftylettuce browser-hrtime

### ISSUE THREAD

**Issue by niftylettuce** [cabinjs/browser-hrtime#4]
Ty!

**Comment by niftylettuce** [comment]
@vltansky Can you transfer this repo to cabinjs org on GitHub and `npm owner add niftylettuce browser-hrtime`?  I will make sure you are collab.

**Comment by vltansky** [comment]
I wrote to you [here](https://github.com/cabinjs/parse-request/pull/5#issuecomment-643045506) that I cant transfer repo without being a member of org (as I understood).

I've already added you as an owner to npm (`npm owner add niftylettuce browser-hrtime`)

**Comment by niftylettuce** [comment]
Sent you an invite!

**Comment by vltansky** [comment]
I've accepted the invite but still getting "You don’t have the permission to create public repositories on cabinjs" when trying to transfer

**Comment by niftylettuce** [comment]
Oh awesome!

**Comment by niftylettuce** [comment]
Done. https://github.com/cabinjs/browser-hrtime
